### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by antoineok** [Zeldown/-974-0001---Novacraft#1]
Tu as la permission d'Alwyn ou de Novacraft pour upload ca sur github?

**Comment by Zeldown** [comment]
> Tu as la permission d'Alwyn ou de Novacraft pour upload ca sur github?

Bonjour, oui en effet je travail sur Novacraft et j’ai eu l’autorisation de mettre en ligne ce code car ce n’est plus la version actuelle

**Comment by antoineok** [comment]
tres bien, par contre, c du code décompilé, ca se vois beaucoup trop facilement

**Comment by Zeldown** [comment]
Oui c’est du code décompiler, c’est volontaire ^^ si tu as le moindre doute je t’invite à m’ajouter sur discord (Zeldown#9963) je t’enverrais les screens ou t’inviterais sur le serveur pour que tu demandes toi même

**Comment by antoineok** [comment]
peux tu envoyer un screen ici de la preuve que tu as la permission?

**Comment by Zeldown** [comment]
Tu veux quoi comme preuve ? L’accord écrit du fondateur du serveur ça te va ?

**Comment by antoineok** [comment]
oui

**Comment by antoineok** [comment]
s'il te plait

**Comment by Zeldown** [comment]
Oki

**Comment by Zeldown** [comment]
Le fondateur va répondre ici directement

**Comment by Zeldown** [comment]
![A3910D8A-E133-4257-8956-BA2DB8CA827D](https://user-images.githubusercontent.com/42982613/93630574-80fdc680-f9ea-11ea-97fd-eebd42c7d30c.jpeg)

**Comment by antoineok** [comment]
ok, tres bien, je vois pas de soucis, désolé du dérangement

**Comment by Zeldown** [comment]
Aucun soucis, bonne soirée
